### ISSUE TITLE
lbforaging 2.0.0 seems does not have Foraging-8x8-2p-3f-v2

### ISSUE THREAD

**Issue by tahirbb** [marl-book/codebase#24]
lbforaging 2.0.0 seems does not have Foraging-8x8-2p-3f-v2

I successfully execute run.py by installing lbforaging 1.1.1

**Comment by LukasSchaefer** [comment]
Hi, thanks for raising the issue. 

We recently updated several libraries, including the LBF environment, to use the `gymnasium` libary instead of the deprecated `gym` library. Due to this update, this codebase (which still uses `gym`) does not work with the most recent version of LBF. We suggest, as you already found, to use the most recent previous LBF version (< 2.0.0).

We intend to update this codebase in near time to also use the new `gymnasium` library which will fix these issues!

**Comment by LukasSchaefer** [comment]
Hi! Just wanted to ping here since we have now also updated this codebase to work with `gymnasium` and thus works with the newest version of the LBF environment (note all lbf environments that are registered are called `...-v3`.
